trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Test'
  displayName: 'Test app'
  jobs:            
  - job: RunLoadTests
    displayName: 'Run load tests'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
    - group: Release
    steps:
    - script: |
        wget -c https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$(jmeterVersion).tgz
        tar -xzf apache-jmeter-$(jmeterVersion).tgz
      displayName: 'Install Apache JMeter'
    - script: apache-jmeter-$(jmeterVersion)/bin/./jmeter -n -t LoadTest.jmx -o Results.xml -Jhostname=$(STAGING_HOSTNAME)
      displayName: 'Run Load tests'
    - script: dir
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: dir $(System.DefaultWorkingDirectory)
    - publish: '$(System.DefaultWorkingDirectory)/Results.xml'
      artifact: results
    